CREATE TABLE Artworks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT user_ibfk FOREIGN KEY (userId) REFERENCES Users(id)
);
